on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y curl libcurl4-doc libcurl4-openssl-dev \
            libharfbuzz-dev libfribidi-dev libmagick++-dev libpoppler-cpp-dev
          quarto install tinytex

      #- name: Install R
        #uses: r-lib/actions/setup-r@v2
        #with:
          #r-version: 'release'

      #- name: Install R Dependencies
        #uses: r-lib/actions/setup-renv@v2

      - name: Render Only
        uses: quarto-dev/quarto-actions/render@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #target: netlify
          #render: true
          #NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
